apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "raftkv.fullname" . }}-config
data:
  config.toml: |
    id = 1
    raft_listen   = "0.0.0.0:{{ .Values.service.raftPort }}"
    client_listen = "0.0.0.0:{{ .Values.service.clientPort }}"
    metrics_listen = "0.0.0.0:{{ .Values.service.metricsPort }}"
    data_dir = "/data"
    election_timeout_ms = {{ .Values.raft.electionTimeoutMs }}
    heartbeat_ms = {{ .Values.raft.heartbeatMs }}
    tick_ms = {{ .Values.raft.tickMs }}
    snapshot_entries_threshold = {{ .Values.raft.snapshotEntriesThreshold }}
    pre_vote = {{ .Values.raft.preVote }}

    {{- range $i, $_ := until (int .Values.replicas) }}
    [[peers]]
    id = {{ add1 $i }}
    raft_addr = "http://{{ include "raftkv.fullname" $ }}-{{ $i }}.{{ include "raftkv.fullname" $ }}:{{ $.Values.service.raftPort }}"
    {{- end }}
