apiVersion: v1
kind: Service
metadata:
  name: {{ include "raftkv.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "raftkv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "raftkv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: raft
      port: {{ .Values.service.raftPort }}
    - name: client
      port: {{ .Values.service.clientPort }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "raftkv.fullname" . }}-client
  labels:
    app.kubernetes.io/name: {{ include "raftkv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "raftkv.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: client
      port: {{ .Values.service.clientPort }}
