import Select from "../components/common/Select";
import {ArrowRightLeft,DatabaseBackup,Plus,Server,Trash2} from "lucide-react";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {api} from "../lib/api";
import {useCluster} from "../hooks/useCluster";
import {formatBytes,formatNumber} from "../lib/format";
import type {AddMemberRequest} from "../types/api";
import Panel from "../components/common/Panel";
import ConfirmDialog from "../components/common/ConfirmDialog";
import AppearanceSettings from "../components/common/AppearanceSettings";
export default function AdministrationPage(){
 const queryClient=useQueryClient();const cluster=useCluster();const snapshots=useQuery({queryKey:["snapshots"],queryFn:api.getSnapshots});
 const [transferTarget,setTransferTarget]=useState<number|null>(null);const [removeTarget,setRemoveTarget]=useState<number|null>(null);const [confirmFlush,setConfirmFlush]=useState(false);const [adding,setAdding]=useState(false);const [member,setMember]=useState<AddMemberRequest>({id:4,role:"learner",raftAddress:"",clientAddress:"",adminAddress:""});
 const invalidate=()=>Promise.all([queryClient.invalidateQueries({queryKey:["cluster"]}),queryClient.invalidateQueries({queryKey:["snapshots"]})]);
 const backup=useMutation({mutationFn:api.downloadBackup,onSuccess:blob=>{const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="backup.rkv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});const snapshot=useMutation({mutationFn:api.triggerSnapshot,onSuccess:invalidate});const transfer=useMutation({mutationFn:(targetId:number)=>api.transferLeadership({targetId}),onSuccess:invalidate});const remove=useMutation({mutationFn:api.removeMember,onSuccess:invalidate});const add=useMutation({mutationFn:()=>api.addMember(member),onSuccess:async()=>{setAdding(false);await invalidate();}});const flush=useMutation({mutationFn:()=>api.executeCommand({command:"FLUSHDB",confirmed:true}),onSuccess:async result=>{if(!result.success)throw new Error(result.display);await Promise.all([invalidate(),queryClient.invalidateQueries({queryKey:["keys"]})]);}});
 const error=backup.error??cluster.error??snapshots.error??snapshot.error??transfer.error??remove.error??add.error??flush.error;const busy=snapshot.isPending||transfer.isPending||remove.isPending||add.isPending||flush.isPending;
 if(!cluster.data)return <div className="stack-xl"><AppearanceSettings/><div className={`page-state ${cluster.isError?"page-state--error":""}`}>{cluster.error?.message??"Loading administration"}</div></div>;
 const members=cluster.data.members??cluster.data.nodes.map(n=>({id:n.nodeId,role:"voter" as const,raftAddress:n.raftAddress??"",clientAddress:n.clientAddress,adminAddress:n.adminAddress}));
 return <div className="stack-xl">
  <AppearanceSettings/>
  {error && <div role="alert" className="feedback feedback--error">{error.message}</div>}
  <div className="admin-grid">
   <Panel title="Cluster membership" description="Join as learner, catch up, then promote through joint consensus." action={<button className="button button--primary button--small" disabled={busy} onClick={()=>setAdding(!adding)}><Plus size={14}/>Add member</button>}>
    {adding && <form className="member-form" onSubmit={event=>{event.preventDefault();add.mutate();}}><label>Node ID<input type="number" min="1" required value={member.id} onChange={event=>setMember({...member,id:Number(event.target.value)})}/></label><label>Role<Select aria-label="Member role" value={member.role} onChange={value=>setMember({...member,role:value as AddMemberRequest["role"]})} options={[{value:"learner",label:"Learner"},{value:"voter",label:"Promote existing learner"}]}/></label>{(["raftAddress","clientAddress","adminAddress"] as const).map(name=><label key={name}>{name}<input required value={member[name]??""} onChange={event=>setMember({...member,[name]:event.target.value})}/></label>)}<label>Peer certificate SHA256 (for mTLS)<input value={member.certificateSha256??""} onChange={event=>setMember({...member,certificateSha256:event.target.value})}/></label><button className="button button--primary" disabled={busy}>Submit membership change</button></form>}
    <div className="member-list">{members.map(m=>{const n=cluster.data!.nodes.find(n=>n.nodeId===m.id);return <div key={m.id} className="member-row"><div className="member-row__identity"><div className="node-card__icon"><Server size={15}/></div><div><strong>Node {m.id}</strong><span>{m.raftAddress}</span></div></div><div className="member-row__meta"><span>{m.role} · {n?.role??"unknown"}</span><span>Applied {formatNumber(n?.appliedIndex)}</span></div><div className="inline-actions">{m.role==="voter"&&m.id!==cluster.data!.leaderId&&<button className="button button--ghost button--small" disabled={busy||n?.health==="unreachable"} onClick={()=>setTransferTarget(m.id)}><ArrowRightLeft size={13}/>Transfer leader</button>}{m.role==="learner"&&<button className="button button--ghost button--small" disabled={busy} onClick={()=>{setMember({...m,role:"voter"});setAdding(true);}}>Promote</button>}<button className="button button--danger-ghost button--small" disabled={busy||members.length===1} onClick={()=>setRemoveTarget(m.id)}><Trash2 size={13}/>Remove</button></div></div>;})}</div>
   </Panel>
   <Panel title="Local snapshots" description="Durable state-machine checkpoints on the receiving node." action={<button className="button button--primary button--small" disabled={busy} onClick={()=>snapshot.mutate()}><DatabaseBackup size={14}/>{snapshot.isPending?"Creating snapshot":"Trigger snapshot"}</button>}><div className="snapshot-list">{snapshots.isLoading && <p>Loading snapshots</p>}{snapshots.data?.length===0 && <p>No snapshots retained.</p>}{snapshots.data?.map(s=><article key={s.id} className="snapshot-row"><div><strong>Index {formatNumber(s.lastIncludedIndex)}</strong><span>Term {s.lastIncludedTerm}</span></div><div><span>Size</span><strong>{formatBytes(s.sizeBytes)}</strong></div><div><span>Created</span><strong>{s.createdAt?new Date(s.createdAt).toLocaleString():"Unavailable"}</strong></div></article>)}</div></Panel>
  </div>
  <Panel title="Backup and recovery" description="Download a checked logical checkpoint from the leader."><button className="button button--primary" disabled={backup.isPending} onClick={()=>backup.mutate()}>Download backup</button><p>Restore is an offline operation into an empty data directory. Use the operator CLI to explicitly bootstrap a new cluster, then join other members as learners.</p></Panel>
  <Panel title="Danger zone" description="These operations change replicated state."><div className="danger-zone"><div><strong>Flush replicated database</strong><p>Delete every key through Raft. This operation cannot be undone.</p></div><button className="button button--danger" disabled={busy} onClick={()=>setConfirmFlush(true)}>Flush database</button></div></Panel>
  <ConfirmDialog open={transferTarget!==null} title="Transfer leadership" description={`Transfer leadership to Node ${transferTarget}? Proposals may pause briefly.`} confirmLabel="Transfer leadership" onClose={()=>setTransferTarget(null)} onConfirm={()=>transferTarget!==null&&transfer.mutate(transferTarget)}/>
  <ConfirmDialog open={removeTarget!==null} title="Remove voting member" description={`Remove Node ${removeTarget} through joint consensus? This changes cluster quorum.`} confirmLabel="Remove member" danger onClose={()=>setRemoveTarget(null)} onConfirm={()=>removeTarget!==null&&remove.mutate(removeTarget)}/>
  <ConfirmDialog open={confirmFlush} title="Flush replicated database" description="Permanently delete all keys through Raft?" confirmLabel="Flush database" danger onClose={()=>setConfirmFlush(false)} onConfirm={()=>flush.mutate()}/>
 </div>;
}
