syntax = "proto3";

package raftkv.admin.v1;

service Admin {
  rpc Status (StatusRequest) returns (StatusResponse);
  rpc TriggerSnapshot (TriggerSnapshotRequest) returns (TriggerSnapshotResponse);
}

message StatusRequest {}

message StatusResponse {
  uint64 node_id = 1;
  string role = 2;
  uint64 term = 3;
  uint64 commit_index = 4;
  uint64 applied_index = 5;
  uint64 last_log_index = 6;
  uint64 leader_id = 7;
  repeated NodeInfo members = 8;
}

message NodeInfo {
  uint64 id = 1;
  string addr = 2;
  bool   voter = 3;
}

message TriggerSnapshotRequest {}
message TriggerSnapshotResponse { bool accepted = 1; }
